["protostar.config"]
protostar_version = "0.3.1"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["src", "lib/cairo_contracts/src"]

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.local.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"
feeder_gateway_url="http://127.0.0.1:5050/"
network="alpha-goerli"
network_opt="--network alpha-goerli --gateway_url http://127.0.0.1:5050 --feeder_gateway_url http://127.0.0.1:5050"


[profile.mainnet.protostar.deploy]
network="alpha-mainnet"

["protostar.contracts"]
timestamp_based_account = [
    "src/onlydust/accounts/timestamp_based_account/account.cairo",
]
nonce_2d_account = [
    "src/onlydust/accounts/nonce_2d_account/account.cairo",
]
